### ISSUE TITLE
iOS 9 Compatibility

### ISSUE THREAD

**Issue by ghost** [moengage/MORichNotification#1]
Currently it is crashing on iOS 9.3, not sure about earlier versions.
Here are the crash logs:
```
dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /Users/berdikhan/Library/Developer/CoreSimulator/Devices/99A973A0-23E0-45EF-89E2-55484DB72F29/data/Containers/Bundle/Application/4751A5AD-FE6D-44B8-BBEE-49C2D82F90B5/testApp.app/Frameworks/MORichNotification.framework/MORichNotification
  Reason: image not found
```
Here is my Podfile:
```
use_frameworks!

target 'testApp' do
    use_frameworks!
    platform :ios, '9.0'
    pod 'MoEngage-iOS-SDK'
end

target 'NotificationService' do
  platform :ios, '10.0'
  pod 'MORichNotification'
end
```

Most probably you need to mark UserNotifications framework as `-weak_framework`.

Thank you

**Comment by berdikhan-fave** [comment]
You can refer to this podspec file https://github.com/CleverTap/CTNotificationService/blob/master/CTNotificationService.podspec

**Comment by ChengappaMoEngage** [comment]
Hi @berdikhan-fave, Are you getting this error in your notification service extension OR from App target. Notification Service Extension is only supported from iOS10 and above, and it will need User Notifications framework to work, therefore haven't made it as weak_framework. can you please confirm if your Notification Service Extension's deployment target is set to iOS 10 and above.

**Comment by berdikhan-fave** [comment]
I am getting it from App target and my Notification Service extension deployment target is 10.0. Above example from CTNotificationService.podspec should solve the issue.

**Comment by ChengappaMoEngage** [comment]
In case you are getting it from your app target, then please refer to this [link](https://docs.moengage.com/docs/push-notification-implementation#section-adding-usernotifications-framework), this should resolve for now. 

I will move UserNotifications framework to weak_framework, for our [core SDK ](https://github.com/moengage/MoEngage-iOS-SDK/blob/master/MoEngage-iOS-SDK.podspec) in the next release.

**Comment by ChengappaMoEngage** [comment]
@berdikhan-fave Do confirm if the issue was resolved after setting `UserNotifications` to optional in your App Target.

**Comment by berdikhan-fave** [comment]
I was set to optional already and it didn't help. I am adding your framework manually for now, will move to cocoapods when you release a new version.
Thanks for support
